# EntityManager Configuration v5.1.3
# Blocked items require permission to override 
# Do NOT change Config_Revision unless you want unexpected errors!
Settings:
  Config_Revision: 1.3
  Admin-Alerts: true
  Player-Alerts: true
  Logging: true
Disable:
  Weather:
    Rain: false
    Thunder: false
    Lightning: false
  Interaction:
    PVP: false
    Fishing: false 
    Shooting: false
    Enchanting: false
    Fireworks: false
    Trading: false
  Usage:
    Blocked_Items:
    - Exp_Bottle
    - Fireball
  Dispensing:
    Blocked_Items:
    - Bedrock
    - Diamond_Block
  Other:
    Monster_Spawner_Exp: false
    Monster_Spawner_Drops: false
TimeManager:
  Enabled: false
  Target_Time: 12000
  Set_Every: 100
EggManager:
  Disabled_Eggs:
  - ghast
SpawnManager:
  Disallowed_Mobs:
  - silverfish
  Disallowed_Reasons:
  - lightning
DeathManager:
  Player:
    Keep_Exp: false
  Entity:
    Drop_Exp: true
    Drop_Items: true