name: EntityManager
author: milkywayz 
main: net.milkycraft.em.EntityManager
version: 5.2
commands:   
    entitymanager:      
      aliases: em      
      description: The main command for entitymanager

  