name: EntityManager
author: milkywayz 
main: net.milkycraft.em.EntityManager
version: 5.1.3

commands:
    entitymanager:
      aliases: em
      description: The main command for entitymanager

  